name: Conventional commit messages

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Check the commit message to match the conventions
        run: npx --no -- commitlint --edit "${1}"
