name: Run the tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Install MongoDB
        run: bash ./scripts/mongodb-install.sh

      - name: Start local MongoDB server
        run: mkdir ~/db && mongod --port 27018 --dbpath ~/db

      - name: Run tests
        run: ts-node ./tests/QuickMongo.test.ts
